import {CHARACTERS,HAS_REGION_FRAMES,prepareCharacter} from './region-character.mjs';
import {Maze,Catch,Sling,MAP,SLING,BASKET,velocity,pathPoint,clamp,circleBox} from './core.mjs?v=basket2';
import {installButtonSounds,playSound} from '../site/audio.mjs';
installButtonSounds();
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
const meta={maze:{title:'月宫吃豆人',rule:'在月宫里，找一口甜。',intro:'穿过月宫回廊，吃光月饼。\n小心巡游的灯笼，大月饼可以帮你反击。',rules:'方向键 / WASD 移动，空格暂停。吃完全部月饼过关；碰到灯笼扣一条命，大月饼提供短暂加成。',hint:'可提前按下方向等待路口转弯，反向立即掉头；手机支持方向按钮和滑动。',metric:'剩余月饼',message:'吃光月饼，把团圆带回家。'},catch:{title:'月饼接接乐',rule:'甜的接住，炸的躲开。',intro:'左右移动竹筐，接住从天而降的月饼。\n45 秒一局，三条命，看看能接多少！',rules:'鼠标移动 / 手指拖动 / 左右键控制竹筐。月饼至少 +10 分，每连接 5 个提升倍率（最高 3 倍），炸弹扣一条命，受伤后短暂无敌。漏接不扣命，但会中断连击。',hint:'坚持 45 秒完成挑战；越到后面，下落越快。',metric:'剩余时间',message:'接住月饼攒连击 · 炸弹 −1 命'},sling:{title:'弹弓救月亮',rule:'借一点月光，弹出个团圆。',intro:'把月亮向左下方拉，松手发射。\n撞开月饼墙，触碰小月亮。撞碎一块就会停下，再次发射救出小月亮。',rules:'拖动弹弓上的月亮瞄准，松手发射。也可用下方按钮调整弧线并发射。方向键微调，Enter 发射，空格暂停。',hint:'每次撞击只破坏一块；轨迹线会标出第一次碰撞。三关分别有 5 / 6 / 7 次机会。',metric:'剩余发射',message:'向左下方拉，松手发射。'}};
const images={},engines={maze:Maze,catch:Catch,sling:Sling};let mode=['maze','catch','sling'].includes(location.hash.slice(1))?location.hash.slice(1):'maze';let engine,ready=false,particles=[],popups=[],shake=0,last=performance.now(),visualTime=0,previousState='',held=new Set(),dragging=false,pointerStart=null,best=0;
const requestedRegion=new URLSearchParams(location.search).get('from');
const region=Object.hasOwn(CHARACTERS,requestedRegion)?requestedRegion:'sichuan';
canvas.dataset.region=region;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function load(name,url){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{images[name]=img;resolve();};img.onerror=reject;img.src=url;});}
const frameRegion=HAS_REGION_FRAMES.has(region)?region:'plain';
Promise.all([load('bg','assets/catch-bg.webp'),load('sling','assets/sling-bg.webp'),load('moons','assets/moon-atlas.webp'),load('props','assets/props.webp'),load('basket','assets/back-basket.webp'),load('plain','assets/regions/plain-frames.webp'),load('character',`assets/regions/${frameRegion}-frames.webp`)]).then(()=>{images.character=prepareCharacter(images.character);images.plain=prepareCharacter(images.plain);ready=true;$('action').disabled=false;sync();}).catch(()=>{$('error').hidden=false;$('action').textContent='刷新重试';$('action').disabled=false;$('action').onclick=()=>location.reload();});
function clearInput(){held.clear();dragging=false;pointerStart=null;}
function select(next){clearInput();mode=next;engine=new engines[mode]();particles=[];popups=[];previousState='';try{best=Number(localStorage.getItem('moon-arcade-'+mode))||0;}catch{best=0;}$('best').textContent=best;location.hash=mode;document.querySelectorAll('[data-game]').forEach(b=>{const selected=b.dataset.game===mode;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});$('title').textContent=meta[mode].title;$('rule-title').textContent=meta[mode].rule;$('rules').textContent=meta[mode].rules;$('hint').textContent=meta[mode].hint;$('dpad').hidden=mode==='sling';$('dpad').classList.toggle('catch-pad',mode==='catch');$('sling-controls').hidden=mode!=='sling';canvas.setAttribute('aria-label',meta[mode].title+'。'+meta[mode].rules);sync();}
function sync(){const s=engine.state;$('score').textContent=String(engine.score).padStart(3,'0');$('metric-label').textContent=meta[mode].metric;$('metric').textContent=mode==='maze'?engine.food.size:mode==='catch'?Math.ceil(engine.remaining)+'s':engine.shots;$('hearts').textContent=mode==='sling'?`第 ${engine.level} 关`:'♥ '.repeat(engine.lives).trim();$('hearts').setAttribute('aria-label',mode==='sling'?`第${engine.level}关`:`剩余${engine.lives}条命`);$('pause').disabled=!['running','paused'].includes(s);$('pause').textContent=s==='paused'?'▶':'Ⅱ';$('pause').setAttribute('aria-label',s==='paused'?'继续游戏':'暂停游戏');$('fire').disabled=!ready||s!=='running'||!!engine.ball||engine.rearm>0;
canvas.dataset.audio='on';canvas.dataset.mode=mode;canvas.dataset.state=s;canvas.dataset.score=engine.score;canvas.dataset.x=(mode==='maze'?engine.position().x:engine.x??engine.ball?.x??0).toFixed(2);canvas.dataset.combo=engine.combo??0;canvas.dataset.blocks=engine.blocks?.length??0;
if(s!==previousState){previousState=s;$('overlay').hidden=s==='running';$('overlay-tag').textContent=s==='won'?'月光满满，收获满满':s==='lost'?'月亮歇一会儿':'月亮准备好了';$('overlay-title').textContent=s==='ready'?meta[mode].title:s==='paused'?'稍等一口':s==='won'?(mode==='sling'&&engine.level<3?'小月亮接到了！':'今晚，满载而归！'):'再试一次，也很甜';$('overlay-text').textContent=s==='ready'?meta[mode].intro:s==='paused'?'时间已暂停，月饼也在等你。':`本局得分 ${engine.score}${mode==='catch'?` · 接住 ${engine.caught} 个月饼`:''}`;$('message').textContent=s==='running'?meta[mode].message:s==='paused'?'已暂停':s==='won'?'挑战完成！':s==='lost'?'机会用完了，再来一次吧。':'准备出发';}
$('action').textContent=!ready?'素材加载中…':s==='paused'?'继续赏玩':s==='ready'?'开始游戏':s==='won'&&mode==='sling'&&engine.level<3?'下一关 →':'再来一局';
if(engine.score>best){best=engine.score;$('best').textContent=best;try{localStorage.setItem('moon-arcade-'+mode,String(best));}catch{}}
}
function start(){if(!ready)return;clearInput();engine.start();particles=[];popups=[];last=performance.now();sync();canvas.focus({preventScroll:true});}
function pause(){clearInput();engine.pause();last=performance.now();sync();}
$('action').onclick=()=>{if(engine.state==='paused')pause();else if(engine.state==='won'&&mode==='sling'&&engine.level<3){engine.nextLevel();sync();}else start();canvas.focus({preventScroll:true});};$('restart').onclick=start;$('pause').onclick=pause;
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>select(b.dataset.game));window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(engines[next]&&next!==mode)select(next);});
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('stage').requestFullscreen();}catch{$('message').textContent='当前浏览器不支持全屏，可横屏体验。';}};
function sprite(which,index,x,y,w,h=w){const img=images[which];if(!img)return;const cols=3,rows=which==='props'?2:1;const sw=img.width/cols,sh=img.height/rows;const inset=which==='props'&&index===2?.18:0;ctx.drawImage(img,(index%cols+inset)*sw,(Math.floor(index/cols)+inset)*sh,sw*(1-2*inset),sh*(1-2*inset),x-w/2,y-h/2,w,h);}
function moon(x,y,w,open=false,dir='right',plain=false){ctx.save();ctx.translate(x,y);if(dir==='left')ctx.scale(-1,1);else if(dir==='up')ctx.rotate(-Math.PI/2);else if(dir==='down')ctx.rotate(Math.PI/2);const frames=plain?images.plain:images.character;const img=ready?frames?.[mode==='maze'&&open?0:1]:null;if(img&&ready){const h=w*img.height/img.width;ctx.imageSmoothingEnabled=false;ctx.drawImage(img,-w/2,-h/2,w,h);}else sprite('moons',open?1:0,0,0,w);ctx.restore();}
function panel(x,y,w,h){ctx.fillStyle='#10273dec';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#b99a5f';ctx.lineWidth=2;ctx.strokeRect(x+1,y+1,w-2,h-2);ctx.strokeStyle='#416170';ctx.strokeRect(x+5,y+5,w-10,h-10);}
function label(text,x,y,size=16,color='#eed4a0'){ctx.fillStyle=color;ctx.textAlign='center';ctx.font=`${size}px "PingFang SC",sans-serif`;ctx.fillText(text,x,y);}
const MX=336,MY=137,CELL=32;
function mazeDraw(){panel(MX-13,MY-13,19*CELL+26,15*CELL+26);MAP.forEach((row,y)=>[...row].forEach((v,x)=>{if(v!=='#')return;const px=MX+x*CELL,py=MY+y*CELL;ctx.fillStyle='#173846';ctx.fillRect(px+2,py+2,28,28);ctx.fillStyle='#54868a';ctx.fillRect(px+2,py+2,28,3);ctx.fillStyle='#2c5b69';ctx.fillRect(px+2,py+5,4,23);ctx.fillStyle='#355a60';ctx.fillRect(px+8,py+8,17,15);ctx.fillStyle='#b4a168';if((x+y)%3===0){ctx.fillRect(px+12,py+12,10,3);ctx.fillRect(px+12,py+12,3,8);}}));engine.food.forEach(f=>{const x=MX+f.x*CELL+16,y=MY+f.y*CELL+16;if(f.big){ctx.fillStyle='#ffe38d25';ctx.fillRect(x-15,y-15,30,30);}sprite('moons',2,x,y,f.big?37:29);});engine.ghosts.forEach((g,i)=>{ctx.save();if(g.recoverUntil>engine.tick)ctx.globalAlpha=.3;if(engine.power){ctx.filter='hue-rotate(150deg)';}const v=engine.ghostPosition(g);sprite('props',5,MX+v.x*CELL+16,MY+v.y*CELL+16,43);ctx.restore();});const p=engine.position();ctx.save();if(engine.invincible>0&&engine.tick%2)ctx.globalAlpha=.5;moon(MX+p.x*CELL+16,MY+p.y*CELL+16,43,engine.state==='running'&&Math.floor(visualTime*9)%2===0,p.dir);ctx.restore();
moon(159,330+(!reduced?Math.sin(visualTime)*5:0),190);panel(68,440,184,88);label(CHARACTERS[region],160,470,17);label('沿着月光，找一口甜',160,499,12,'#b9cbd0');sprite('props',5,1093,300,100);panel(991,390,204,118);label('巡游灯笼',1093,418,17);label('大月饼 → 短暂加成',1093,447,13);label(engine.power?'强化 '+(engine.power*.16).toFixed(1)+'s · 追赶灯笼':'绕开它，别掉团圆能量',1093,476,12,engine.power?'#ffdc78':'#b9cbd0');}
function catchDraw(){engine.items.forEach(item=>{ctx.save();ctx.translate(item.x,item.y);ctx.rotate(Math.sin(item.spin)*.12);sprite(item.bomb?'props':'moons',item.bomb?0:2,0,0,item.bomb?75:76);ctx.restore();});ctx.save();if(engine.invincible>0&&Math.floor(visualTime*12)%2)ctx.globalAlpha=.45;const pulse=reduced?0:Math.sin(engine.catchPulse/.22*Math.PI);
ctx.save();ctx.translate(engine.x,BASKET.rimY);const moving=Math.abs(engine.target-engine.x)>1||held.has('left')||held.has('right');ctx.rotate(reduced?0:Math.sin(visualTime*8)*(moving?.035:.009));ctx.scale(1+pulse*.035,1-pulse*.07);if(images.basket)ctx.drawImage(images.basket,-65,-22,130,135);ctx.restore();
moon(engine.x+105,583+pulse*2,145);
ctx.strokeStyle='#8c5327';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(engine.x+47,574);ctx.lineTo(engine.x+69,582);ctx.stroke();ctx.strokeStyle='#dfaf61';ctx.lineWidth=2;ctx.stroke();ctx.restore();label('←',engine.x-86,620,25);label('→',engine.x+195,620,25);if(engine.combo>1){panel(510,117,260,57);label(engine.combo+' 连击 · ×'+Math.min(3,1+Math.floor(engine.combo/5)),640,153,24,'#ffe095');}ctx.fillStyle='#14273b';ctx.fillRect(340,688,600,8);ctx.fillStyle=engine.remaining<10?'#ff8d6a':'#ffe095';ctx.fillRect(340,688,600*engine.remaining/45,8);}
function slingDraw(){// Foreground ledges also define the collision floor.
 for(const [x,w,y] of [[0,430,592],[795,485,520]]){ctx.fillStyle='#203f4c';ctx.fillRect(x,y,w,18);ctx.fillStyle='#7b967e';ctx.fillRect(x,y,w,4);ctx.fillStyle='#b8ac70';for(let i=x+8;i<x+w;i+=46)ctx.fillRect(i,y+4,32,2);}
 engine.blocks.forEach(b=>sprite('props',2,b.x+b.w/2,b.y+b.h/2,b.w));moon(engine.target.x,engine.target.y,85,false,'right',true);if(!reduced){ctx.fillStyle='#ffed9b';for(let i=0;i<4;i++){const a=visualTime*.8+i*Math.PI/2;ctx.fillRect(engine.target.x+Math.cos(a)*56,engine.target.y+Math.sin(a)*44,4,4);}}
 sprite('props',3,SLING.x,535,150,180);for(let i=0;i<Math.min(4,engine.shots-(engine.ball?0:1));i++)moon(42+i*37,567,43);
 if(engine.state==='running'&&!engine.ball&&engine.rearm<=0){const v=velocity(engine.pull);ctx.save();for(let t=.025;t<2.3;t+=.025){const p=pathPoint(v,t);const hit=engine.blocks.some(b=>circleBox(p.x,p.y,23,b));const floor=(p.x<430&&p.y+23>=592||p.x>795&&p.y+23>=520)&&v.vy+SLING.g*t>0;if(hit||floor||p.x>1230||p.y>720){ctx.strokeStyle=hit?'#ffbd70':'#eed49b';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,15,0,Math.PI*2);ctx.stroke();break;}ctx.fillStyle='rgba(255,225,148,.7)';ctx.fillRect(p.x-2,p.y-2,4,4);}ctx.restore();ctx.strokeStyle='#33262d';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(SLING.x-20,SLING.y-7);ctx.lineTo(engine.pull.x,engine.pull.y);ctx.lineTo(SLING.x+20,SLING.y-7);ctx.stroke();moon(engine.pull.x,engine.pull.y,83);const strength=Math.round(Math.hypot(v.vx,v.vy)/(SLING.maxPull*SLING.scale)*100);panel(72,620,270,52);label('力度 '+strength+'% · 拖动微调角度',207,650,15); }
 else if(engine.state==='ready')moon(SLING.x,SLING.y,83);
 if(engine.impact){const b=engine.impact;ctx.save();ctx.globalAlpha=b.life/.4;moon(b.x,b.y,76);ctx.restore();}if(engine.ball){if(!reduced)engine.trail.forEach((p,i)=>{ctx.fillStyle=`rgba(255,225,148,${i/engine.trail.length*.5})`;ctx.fillRect(p.x-3,p.y-3,6,6);});const b=engine.ball;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.t*3);moon(0,0,72);ctx.restore();}
}
function effects(dt){for(const event of engine.drain()){let x=event.x,y=event.y;if(mode==='maze'&&!['win','lose'].includes(event.type)){x=MX+x*CELL+16;y=MY+y*CELL+16;}if(event.text)popups.push({x,y,text:event.text,t:.8,color:event.type==='hurt'?'#ff9387':'#ffe6a0'});if(['hurt','break'].includes(event.type)&&!reduced)shake=event.type==='hurt'?.25:.14;if(mode==='sling'&&event.type==='break')$('message').textContent='撞碎一块！调整角度，再来一发。';if(['eat','catch','combo','break','win','hurt','lose'].includes(event.type))playSound(event.type==='win'?'reveal':event.type==='hurt'||event.type==='lose'?'box':'select');if(!reduced&&['eat','catch','combo','break','win'].includes(event.type)){for(let i=0;i<(event.type==='win'?40:event.type==='break'?26:12);i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:-40-Math.random()*150,t:.4+Math.random()*.5,color:i%2?'#f6c36c':'#fff1b8'});}}if(engine.state==='paused')return;particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=220*dt;p.t-=dt;});particles=particles.filter(p=>p.t>0);popups.forEach(p=>{p.y-=30*dt;p.t-=dt;});popups=popups.filter(p=>p.t>0);shake=Math.max(0,shake-dt);}
function draw(){ctx.clearRect(0,0,1280,720);ctx.imageSmoothingEnabled=false;ctx.save();if(shake>0)ctx.translate(Math.sin(visualTime*80)*4,0);const bg=mode==='sling'?images.sling:images.bg;if(bg)ctx.drawImage(bg,0,0,1280,720);else{ctx.fillStyle='#142b49';ctx.fillRect(0,0,1280,720);}if(mode==='maze'){ctx.fillStyle='#0b192530';ctx.fillRect(0,0,1280,720);mazeDraw();}else if(mode==='catch')catchDraw();else slingDraw();for(const p of particles){ctx.globalAlpha=Math.min(1,p.t*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,5);}ctx.globalAlpha=1;for(const p of popups){ctx.globalAlpha=Math.min(1,p.t*3);label(p.text,p.x,p.y,23,p.color);}ctx.globalAlpha=1;ctx.restore();}
function loop(now){const dt=Math.min((now-last)/1000,.035);last=now;if(engine.state!=='paused')visualTime+=dt;if(ready){engine.update(dt,(held.has('right')?1:0)-(held.has('left')?1:0));effects(dt);sync();}draw();requestAnimationFrame(loop);}
const keys={ArrowRight:'right',d:'right',D:'right',ArrowLeft:'left',a:'left',A:'left',ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down'};
function direction(dir){if(engine.state!=='running')return;if(mode==='maze')engine.direction(dir);else if(mode==='catch')held.add(dir);else engine.aim(engine.pull.x+(dir==='left'?-5:dir==='right'?5:0),engine.pull.y+(dir==='up'?5:dir==='down'?-5:0));}
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||e.metaKey||e.ctrlKey||e.altKey)return;if(e.target.closest('button')&&!keys[e.key])return;if(keys[e.key]){e.preventDefault();direction(keys[e.key]);}if(e.code==='Space'&&!e.repeat){e.preventDefault();pause();}if(e.key==='Enter'&&!e.repeat&&mode==='sling'){e.preventDefault();engine.fire();}});
window.addEventListener('keyup',e=>{if(keys[e.key])held.delete(keys[e.key]);});window.addEventListener('blur',clearInput);
function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*1280/r.width,y:(e.clientY-r.top)*720/r.height};}
canvas.addEventListener('pointerdown',e=>{if(engine.state!=='running')return;const p=point(e);canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);pointerStart=p;if(mode==='catch'){dragging=true;engine.aim(p.x);}else if(mode==='sling'&&!engine.ball&&Math.hypot(p.x-engine.pull.x,p.y-engine.pull.y)<125){dragging=true;engine.aim(p.x,p.y);}});
canvas.addEventListener('pointermove',e=>{if(engine.state!=='running')return;const p=point(e);if(mode==='catch'&&(e.pointerType==='mouse'||dragging))engine.aim(p.x);if(mode==='sling'&&dragging)engine.aim(p.x,p.y);if(mode==='maze'&&pointerStart){const dx=p.x-pointerStart.x,dy=p.y-pointerStart.y;if(Math.hypot(dx,dy)>12){engine.direction(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));pointerStart=p;}}});
canvas.addEventListener('pointerup',()=>{if(mode==='sling'&&dragging)engine.fire();dragging=false;pointerStart=null;});canvas.addEventListener('pointercancel',clearInput);
document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);direction(b.dataset.dir);canvas.focus({preventScroll:true});});b.addEventListener('pointerup',()=>held.delete(b.dataset.dir));b.addEventListener('pointercancel',()=>held.delete(b.dataset.dir));b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();direction(b.dataset.dir);}});b.addEventListener('keyup',()=>held.delete(b.dataset.dir));});
document.querySelectorAll('[data-aim]').forEach(b=>b.onclick=()=>{if(mode==='sling')engine.aim(engine.pull.x,engine.pull.y+(b.dataset.aim==='higher'?8:-8));});document.querySelectorAll('[data-power]').forEach(b=>b.onclick=()=>{if(mode==='sling'){const factor=b.dataset.power==='more'?1.08:.92;engine.aim(SLING.x+(engine.pull.x-SLING.x)*factor,SLING.y+(engine.pull.y-SLING.y)*factor);}});$('fire').onclick=()=>{engine.fire();canvas.focus({preventScroll:true});};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&engine.state==='running')pause();});
select(mode);requestAnimationFrame(loop);

// Preserve the completed hometown scene when returning from the arcade.
const returnParams=new URLSearchParams(location.search);
const returnRegion=returnParams.get('from');
if(Object.hasOwn(CHARACTERS,returnRegion)){
 const back=document.querySelector('header .brand');
 back.href='../#reveal/'+returnRegion+'/'+(returnParams.get('mode')==='explore'?'explore':'search')+'/done';
 back.innerHTML='<span>←</span> 返回家乡月色';
}
